# Generated by Django 5.1.4 on 2024-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedreceipt',
            name='amount',
        ),
        migrations.AlterField(
            model_name='scannedreceipt',
            name='store_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
